import telebot
from telebot import types
import random
import pyotp
import time

# আপনার বটের টোকেন
API_TOKEN = '8766718043:AAG7bJHEyNU53FMNWTw0l6GKsz4f62FutnU'
bot = telebot.TeleBot(API_TOKEN)

# নামের ডাটাবেস
first_names = ["Arif", "Sajid", "Nabil", "Fahim", "Tanvir", "Rohan", "Siam", "Zayan", "Eshan", "Kabir", "Munna", "Sabbir", "Rakib", "Anas", "Hamza", "Adnan", "Jubayer"]
last_names = ["Khan", "Ahmed", "Hossain", "Chowdhury", "Sarker", "Islam", "Mridha", "Talukdar", "Sheikh", "Rahman", "Munshi", "Bhuiyan", "Patwary"]

@bot.message_handler(commands=['start'])
def send_welcome(message):
    markup = types.ReplyKeyboardMarkup(row_width=2, resize_keyboard=True)
    btn1 = types.KeyboardButton('🔘 Name Generator')
    btn2 = types.KeyboardButton('🔑 Get 2FA Code')
    markup.add(btn1, btn2)
    
    welcome_text = (
        f"আসসালামু আলাইকুম {message.from_user.first_name}!\n\n"
        f"🤖 বটটি তৈরি করেছেন: **Daniyal**\n"
        "নিচের বাটনগুলো ব্যবহার করে কাজ শুরু করুন।"
    )
    bot.send_message(message.chat.id, welcome_text, reply_markup=markup, parse_mode='Markdown')

@bot.message_handler(func=lambda message: True)
def handle_buttons(message):
    if message.text == '🔘 Name Generator':
        f_name = random.choice(first_names)
        l_name = random.choice(last_names)
        num = random.randint(100, 99999)
        full_name = f"{f_name} {l_name} {num}"
        bot.send_message(message.chat.id, f"👤 Generated Name: `{full_name}`\n\nBy: Daniyal", parse_mode='Markdown')
        
    elif message.text == '🔑 Get 2FA Code':
        msg = bot.send_message(message.chat.id, "আপনার 2FA Secret Key টি দিন:")
        bot.register_next_step_handler(msg, process_2fa)

def process_2fa(message):
    try:
        secret = message.text.replace(" ", "")
        totp = pyotp.TOTP(secret)
        code = totp.now()
        bot.send_message(message.chat.id, f"✅ Your 2FA Code: `{code}`\n\nGenerated by: Daniyal", parse_mode='Markdown')
    except Exception:
        bot.send_message(message.chat.id, "❌ ভুল কি (Key) দিয়েছেন!")

while True:
    try:
        bot.infinity_polling(timeout=20, long_polling_timeout=10)
    except Exception:
        time.sleep(5)
